### ISSUE TITLE
[Task] Explain how to build documentation locally

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#145]
**Is your task related to a problem? Please describe.**
The Readme.md contains a todo in line 
https://github.com/OpenManufacturingPlatform/sds-sdk/blob/b5ce367e8c3eb514a7fc59e0fbad691c4ae91864/README.md?plain=1#L40
which asks for explaining how to build the anthora documentation locally.
This explanation should be added and the TODO removed.

**Comment by atextor** [comment]
Fixed in #338
