### ISSUE TITLE
[BUG] JSonSubTypes on generated Java classes are incorrect

### ISSUE THREAD

**Issue by DvSmi** [eclipse-esmf/esmf-sdk#177]
**Describe the bug**
When you're creating a Model which contains an Entity 'A' , extending Entity 'B', extending AbstractEntity 'C', the Java code generation  should create an abstract class named `abstract class C`, including `JsonSubTypes` annotations.
The annotations should contain information for both, 'A' and 'B', like:
```
@JsonSubTypes( { 
@JsonSubTypes.Type( value = B.class, name = "B" ),
@JsonSubTypes.Type( value = A.class, name = "A" ) } )
```
At the moment this is not correctly done as only Type B is shown.

**Comment by RaMisess** [comment]
Especially when considering the possibility of changing the AbstractEntity C into a regular entity, after which no annotations are generated anymore and the JSON polymorphism is completely gone.

Any thoughts on the issue @DvSmi and @atextor ?

**Comment by DvSmi** [comment]
The problem came up during the code generation and serializing.  
If i recall it correctly, then transitivity was not given with those annotations. So your proposed solution with having Subtypes on class B and on class C won't work. 
If i remember it incorrectly, then either solution is fine, as long as the serialization works without adjustments.
