### ISSUE TITLE
[Task] Coloring of operations in CLI HTML Documentation

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#212]
**Is your task related to a problem? Please describe.**
The color yellow for documetnation of operations is difficult to read - see screenshot
seems also inconsistent to the documentation of properties and entities (the headline is yellow but text is black).

![grafik](https://user-images.githubusercontent.com/59824205/184888833-33148a48-1d60-4d1e-add6-aa4dfd022e10.png)

This is how it looks for properties:
![grafik](https://user-images.githubusercontent.com/59824205/184889366-9793468d-cbd5-4ddf-9582-49cae649e100.png)

**Describe the solution you'd like**
make only headline yellow, rest black (like for properties)

**Describe alternatives you've considered**
--

**Comment by atextor** [comment]
Can you please elaborate on where this happens? Is this the HTML generated for an Aspect Model? When calling `bamm-cli aspect MyAspect.ttl to html`, the resulting HTML or CSS does not contain these colors.

**Comment by BirgitBoss** [comment]
I assume that Catena-X is using a different .css style information. See e.g. https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.1/gen/BatteryPass.html (there is no operation in this model, I did not find a model with an operation). So this issue is not relevant for ESMF default generation.

I will close the issue.
