### ISSUE TITLE
[Task] Add generator for AAS submodels

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-sdk#280]
**Is your task related to a problem? Please describe.**
Currently, the SDK provides the capability to generate an Asset Administration Shell (AAS) submodel template from an Aspect Model. It would be most useful for users of AAS and Aspect Models if there was also a way to generate an AAS submodel. The generator should take as input a List of Pair(Aspect Model, JSON payload that corresponds to the Aspect Model) and what other context information is/could be needed on top of that to generate a submodel.

**Describe the solution you'd like**
This functionality should be added to the already-existing sds-aspect-model-aas-generator module. Corresponding switches to call this functionality should also be added to the bamm-cli.

**Comment by bs-jokri** [comment]
@atextor PR is merge so I assume this ticket can be closed

**Comment by atextor** [comment]
Yes, the PR didn't properly link to the issue.
