### ISSUE TITLE
[Task] Improve AASGenerator error message output for Properties

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#291]
**Is your task related to a problem? Please describe.**
The AASGenerator uses the toString() method of DefaultProperty [1] to report to the user a problem with recursive properties in a model. The current implementation of DefaultProperty.toString() does not show the name of the Property as it is given in the model. Thus, the user can only guess which Property is the actual problem.

[1] io/openmanufacturing/sds/metamodel/impl/DefaultProperty.java:119

**Describe the solution you'd like**
The toString method should, instead or additionally to the class name of DefaultProperty also print the property name as it is used in the model.

**Comment by atextor** [comment]
IMO, creating some representation format for a model object should be done where it's used, i.e., the formatting should take place in the AASGenerator in this case. The model object's `toString()` methods are usually used for debugging output.
