### ISSUE TITLE
[Task] Add JSON output support to AAS generator module and SAMM CLI

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#292]
**Is your task related to a problem? Please describe.**
currently the AAS Generator module only supports AASX and XML. It is required to also generate JSON output.

**Describe the solution you'd like**
The AAS4J lib supports json generation. As soon as the this lib is integrated the json output can be implemented as an additional format option in the SAMM-CLI.

DEPENDS on #289

**Comment by bs-jokri** [comment]
corresponding PR: https://github.com/eclipse-esmf/esmf-sdk/pull/293

**Comment by bs-jokri** [comment]
@atextor PR is merge so I assume this ticket can be closed

**Comment by atextor** [comment]
If that PR addresses this issue, then yes. It was not mentioned there.
