### ISSUE TITLE
[BUG] Using AspectModelValidator fails to validate models with Point3d

### ISSUE THREAD

**Issue by external-Bogdan-Toma** [eclipse-esmf/esmf-sdk#311]
**Describe the bug**
Using AspectModelValidator fails to validate models with bamm-e:Point3d.
Having 2 model elements in different namespaces extending bamm-e:Point3d with properties having same name fails to validate.

Violations messages:
The Entity ':Point3dWithLabelEntity' contains Property 'label' which causes ambiguity in combination with the 'urn:bamm:com.example.point3d1:0.0.1#Point3dWithLabelEntity' Entity.,
The Entity 'urn:bamm:com.example.point3d1:0.0.1#Point3dWithLabelEntity' contains Property 'label' which causes ambiguity in combination with the ':Point3dWithLabelEntity' Entity.

**Where**
sds-aspect-model-validator version 2.1.3.

**Additional context**
Attached zip with tests and models.
[org.example.validation.test.zip](https://github.com/eclipse-esmf/esmf-sdk/files/10743435/org.example.validation.test.zip)
Use test class: org.example.ValidationTest.

**Comment by RaMisess** [comment]
The validation of extension scenarios like this has been relaxed for https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/issues/161, this should fix this issue as well.
