### ISSUE TITLE
[BUG] AAS Mapping rules are not correct anymore as of AAS spec v3

### ISSUE THREAD

**Issue by andreas-schilling** [eclipse-esmf/esmf-sdk#314]
**Describe the bug**
The mapping rules described in the aspect tooling docs describe the situation prior to v3 of the AAS spec, where both collections (as in lists/sets/...) and structures of properties have been described with a `SubModelElementCollection` rather than the new distinct types `SubModelElementCollection` and `SubModelElementList`.

**Where**
`java-aspect-model-tooling.adoc`

**Comment by atextor** [comment]
Since AAS v3 is not released yet, I'd wait with merging this PR until then.

**Comment by chris-volk** [comment]
AAS v3 has been released

**Comment by atextor** [comment]
Fixed in #312
