### ISSUE TITLE
[BUG] CLI Validator - see attribute with http leads to error

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#322]
**Describe the bug**
a value for see-attribute that consists of a non-resolvalbe http-value leads to an error. However, in the case of http://admin-shell.io/vdi/2770/1/0/Documentation etc. these Identifier are meant as logical identifier only
This should not be listed as an error but as information only by the validator.

**Where**
Validation of aspect models with elements with see-attribute containing a http-value like e.g.. "http://admin-shell.io/vdi/2770/1/0/Documentation"

Error message:
![grafik](https://user-images.githubusercontent.com/59824205/224564423-2180da40-3979-4466-b32d-55055a42b7ac.png)

**Comment by RaMisess** [comment]
@BirgitBoss Can you please provide an example triggering the validation error? The test models I came up with to investigate the problem all pass the validation without error. It also looks like the HTTP-like values are being filtered out by the code. It looks like only a very specific use case can trigger the validation error.

**Comment by BirgitBoss** [comment]
it seems the error was already resolved -:) This issue can be closed

This would have been an example:
:Characteristic1 a bamm:Characteristic;
    bamm:dataType xsd:string;
    bamm:see <http://admin-shell.io/vdi/2770/1/0/Documentation/Characteristic>.
:AspectError322 a bamm:Aspect;
    bamm:properties (:myExampleProperty);
    bamm:operations ();
    bamm:events ();
    bamm:description "Example for https://github.com/eclipse-esmf/esmf-sdk/issues/322"@en;
    bamm:see <http://admin-shell.io/vdi/2770/1/0/Documentation>.
:myExampleProperty a bamm:Property;
    bamm:characteristic :Characteristic1;
    bamm:see <http://admin-shell.io/vdi/2770/1/0/Documentation/exampleProperty>.
