### ISSUE TITLE
[BUG] Aspect Model Editor 4.3.0 does not store AbstractEntity-Property relations

### ISSUE THREAD

**Issue by FlorianPatzerFraunhoferIOSB** [eclipse-esmf/esmf-sdk#356]
The Aspect Model Editor 4.3.0 cannot handle AbstractEntity->Property relations.
A connection between AE and P, c.f. AbstractEntity1 and property2 in the following image, will neither be stored in the [turtle export](https://github.com/eclipse-esmf/esmf-sdk/files/11421946/AE-P-test.ttl.txt) nor in the json export. 
![AE-P-relation_before_saving](https://user-images.githubusercontent.com/95237454/236847855-8decbc65-029f-4d12-84e5-692e9f540282.PNG)

Thus, it is gone after loading the aspect model from the ttl-file:
![AE-P-relation_after_saving_and_loading](https://user-images.githubusercontent.com/95237454/236847854-28b0f555-ef92-4f7d-9f09-51310a143ff7.PNG)

**Comment by atextor** [comment]
Since this is a bug in the Aspect Model Editor, it will be tracked there from now on: https://github.com/eclipse-esmf/esmf-aspect-model-editor/issues/45
