### ISSUE TITLE
[BUG] Aspect Model Editor 4.3.0 does not interpret URNs as expected

### ISSUE THREAD

**Issue by FlorianPatzerFraunhoferIOSB** [eclipse-esmf/esmf-sdk#357]
Given a URN like `urn:my-nid:org.mynid.aspect-models:test-model:0.0.1 .` as prefix in a [turtle file](https://github.com/eclipse-esmf/esmf-sdk/files/11422109/URN-test.ttl.txt), the Aspect Model Editor 4.3.0 incorreclty interprets it as follows:
![URN-interpretation-issue1](https://user-images.githubusercontent.com/95237454/236853966-6b0acbb7-a0b1-48ad-b1eb-dc209251de67.PNG)

and further cannot export the file anymore:
![URN-interpretation-issue2](https://user-images.githubusercontent.com/95237454/236854254-0da2f511-0399-4b73-b73e-b8108a6dd4c3.PNG)
(received when trying to export the file without any changes as a turtle file.

**Comment by atextor** [comment]
Hi @FlorianPatzerFraunhoferIOSB ,
this is not a valid Aspect Model URN and not expected to work, it must follow this pattern:
`urn:samm:<namespace>:<version>#<element-name>`.
Please refer to the [specification](https://eclipse-esmf.github.io/samm-specification/2.0.0/namespaces.html#aspect-model-element-identifiers-definition) for details.

However, the Aspect Model Editor should report this more clearly; this will be tracked here: https://github.com/eclipse-esmf/esmf-aspect-model-editor/issues/46.

**Comment by FlorianPatzerFraunhoferIOSB** [comment]
Got it, thank you! I didn't realize the "samm" nid is mandatory.
