### ISSUE TITLE
[BUG] SAMM CLI validator should use defined REGEX also for provided example values

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#384]
**Describe the bug**
Currently it is possible to define example values for a characteristic, which is not adhering to a defined regex of that characteristic.

Expected:
the SAMM-SDK validator hinders to 

**Where**
SAMM-CLI 2.2.2

**Additional context**
Several Problems found in https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main
Relates to https://github.com/eclipse-esmf/esmf-sdk/issues/372

**Comment by birgitZF** [comment]
I think such a feature of the validator would be highly appreciated as otherwise we might produce semantically wrong SAMM models without being aware of any errors
