### ISSUE TITLE
[BUG] No Developer Documentation found for v2.3.1 of ESMF SDK

### ISSUE THREAD

**Issue by bs-jokri** [eclipse-esmf/esmf-sdk#412]
**Describe the bug**
The link 
https://eclipse-esmf.github.io/esmf-developer-guide/2.3.1/tooling-guide/samm-cli.html

does not point to an existing page, even though v2.3.1 is released.

Latest version of developer guide is 2.2.3
https://eclipse-esmf.github.io/esmf-developer-guide/2.2.3/index.html

**Comment by atextor** [comment]
Fixed by https://github.com/eclipse-esmf/eclipse-esmf.github.io/pull/20.
