### ISSUE TITLE
[Bug] SAMM model to AAS Submodel

### ISSUE THREAD

**Issue by spnazf** [eclipse-esmf/esmf-sdk#431]
Hi Team, we are trying to add the samm model as submodel to an existing asset administration shell in basyx server. We are using esmf-sdk to generate AAS from SAMM model (.ttl files). Able to generate AAS file as XML but still facing issue with .aasx files. Its not getting generated. Is it technically possible to  do? Is there any straightforward way to achieve this ? Kindly provide some input. Thanks in advance.

**Comment by chris-volk** [comment]
Hi @spnazf , 
yes, this is a feature, see https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/java-aspect-tooling.html#calling-aas-generation-from-java (and https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html ). 
How do you mean "not getting generated"

Could you please provide an example with your expected result and actual result including all relevant files and the used version of the sdk?

- the existing asset admin shell (aasx) file
- the Aspect Model (ttl file)

Please be aware that the issue that you are reporting may originate from https://github.com/admin-shell-io/submodel-templates/issues/37 .

**Comment by BirgitBoss** [comment]
see also https://github.com/eclipse-esmf/esmf-sdk/issues/432 for identified bugs in the SAMM2AAS generator

**Comment by Yauhenikapl** [comment]
Hi @spnazf,

Could you please provide your SAMM model for reproducing that behavior, what you describe before?

Thanks,
Best Regards!

**Comment by Yauhenikapl** [comment]
Hi @spnazf,

Do you have any updates?

Thanks,
Best Regards!

**Comment by atextor** [comment]
Issue is not reproducible with the given information. I'm closing the issue, feel free to reopen with more details on what exactly fails, for which input models, with which error messages etc.
