### ISSUE TITLE
[Task] CLI SAMM2AAS Generator: add samm:description to ConceptDescription IEC61360/definition

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#434]
**Is your task related to a problem? Please describe.**

Instead of writing the samm:definition to Property/description samm:definition shall be mapped to data specification IEC62360 definition, because it belongs to semantics

`<dataSpecificationContent>
						<dataSpecificationIec61360>`
...
`							<definition>
								<langStringDefinitionTypeIec61360>
									<language>X-33DQI-g</language>
									<text>something_2ae95f9f</text>
								</langStringDefinitionTypeIec61360>
							</definition>`

**Comment by KobOp** [comment]
@BirgitBoss according to SAMM CLI 2.4.1, the property' samm:description is mapped to aas:property, whereas the dataSpecificationIec61360 contains the property's characteristic description. 
E.g.
```
:speed a samm:Property ;
   samm:preferredName "speed"@en ;
   samm:description "speed of vehicle"@en ;
   samm:characteristic :Speed .
:Speed a samm-c:Measurement ;
   samm:preferredName "speed"@en ;
   samm:description "Scalar representation of speed of an object in kilometers per hour."@en ;
   samm:dataType xsd:float ;
   samm-c:unit unit:kilometrePerHour .
```
becomes
```
<aas:property>
  <aas:idShort>id_speed</aas:idShort>
  <aas:displayName>...</aas:displayName>
  <aas:description>
	<aas:langStringTextType>
	  <aas:language>en</aas:language>
	  <aas:text>speed of vehicle</aas:text>
	</aas:langStringTextType>
  </aas:description>
  <aas:semanticId>...</aas:semanticId>
  ...
</aas:property>
...
<aas:conceptDescription> 
  <aas:dataSpecificationIec61360>
    <aas:preferredName>...</aas:preferredName>
    <aas:shortName>...</aas:shortName>
	<aas:unit>kilometrePerHour</aas:unit>
	  <aas:definition>
		<aas:langStringDefinitionTypeIec61360>
		  <aas:language>en</aas:language>
		  <aas:text>Scalar representation of speed of an object in kilometers per hour.</aas:text>
		</aas:langStringDefinitionTypeIec61360>
	  </aas:definition>
  </aas:dataSpecificationIec61360>
</aas:conceptDescription>
```
To move the property description from aas:property to the aas:dataSpecifiationIed61360, the characteristic description would be lost. @atextor do you have an idea to keep both semantic descriptions?

**Comment by BirgitBoss** [comment]
I think we should accept that information is lost when converting a SAMM model into an Submodel Template using IEC61360 data specification.
