### ISSUE TITLE
[Task]: Include SAMM version in gen files / Include model version in gen files

### ISSUE THREAD

**Issue by catroest** [eclipse-esmf/esmf-sdk#485]
**Is your task related to a problem? Please describe.**
The application developers would like to know what version of SAMM was used in the modeling. Also they want to know what version of the model itself (io.catenax.generic.digital_product_passport_2.0.0) was used. We know this information is saved in the turtle file.

**Describe the solution you'd like**
Include a header (at least) in the json payload.
Possible examples:
`<?language version="2.0.0" language type="SAMM"?>`
and
`<?model version="io.catenax.generic.digital_product_passport_2.0.0"?>`

**Additional context**
Example of a header for encoding: `<?xml version="1.0" encoding="UTF-8"?>`

**Comment by catroest** [comment]
Hello,

yes I mean the generated files.
The problem came up in the recent CATENA-X project were the SAMM tooling is used.
The solution to include it in the schema would be helpful, I think I misinterpreted the payload. I will foreward the discussion on the #340 to the application provider responsible.

This ticket can now be closed, as the topic is discussed in another ticket.

**Comment by matbmoser** [comment]
I created a proposal here https://github.com/eclipse-esmf/esmf-sdk/issues/491. In this way we can get way more information.
