### ISSUE TITLE
[Task] SAMM CLI: Make native binaries easier to download via documentation

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-sdk#494]
On https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html and the release page of the sdk , the
native binaries for win and linux (and macOS see https://github.com/eclipse-esmf/esmf-sdk/issues/493 ) shall be easier to find and download.

1. Remove incorrect information from samm-cli.html stating that java is required
2. include version number for binaries, e.g. [samm-cli-windows.zip](https://github.com/eclipse-esmf/esmf-sdk/releases/download/v2.4.2/samm-cli-windows.zip) -> samm-cli-2.4.2-windows.zip
3. explicitly link the binaries for the platforms in samm-cli.html so that people do not confuse it with the other 5 (non-binary) assets starting with samm-cli-.

**Comment by chris-volk** [comment]
... perhaps add further platform related usage instructions (windows: extract zip to location of your choice, run the contained samm.exe from windows command line)

**Comment by atextor** [comment]
The file names should not only contain the version, but also the system architecture (e.g.  x86_64).
