### ISSUE TITLE
[BUG] CLI - generate png and svg - buggy display of stereotype 

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#511]
**How: List of performed steps**
When generating .png or .svg with the CLI the stereotype is not with `<<` and `>>` but some other special character

![image](https://github.com/eclipse-esmf/esmf-sdk/assets/59824205/cdaeeeab-b8cd-4c6b-a10c-e315328f4b0d)

`samm aspect C:\__localWork\SAMM\SDK_CLI\samm\org.eclipse.examples\1.0.0\Movement.ttl to png --output ../gen/Movement.png >> ../log/samm.log`

**What: Actual result vs expected result**
 `<<Aspect>>` 

**Where: (e.g. component, version, url, your system info)**

samm-cli - Semantic Aspect Meta Model Command Line Tool
Version: 2.5.0
Build date: 2024-01-23T10:02:37Z
Git commit: 3538f0357364a71c4e4e4151d42f687bf996f162

**Input (files/screenshots)**

I used the standard Movement.ttl that is coming with the Aspect Model Editor as test input

**Comment by atextor** [comment]
Fixed together with the changes in #530.
