### ISSUE TITLE
[BUG] CLI aasx Generation - semanticId either ExternalREference or ModelReference

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#523]
**How: List of performed steps**
The the current version the semanticId are a combination of externalReference and ModelReference. Sometimes the semanticId is an ExternalReference, sometimes it is a ModelReference (probably correct only for Submodel itself but not for its sub-elements).

![image](https://github.com/eclipse-esmf/esmf-sdk/assets/59824205/82356f8e-1ca6-440e-80fa-d6b4bb77a1f3)

If a ConceptDescription is reference the value is "ModelReference" and not "ExternalReference"
For an "ExternalReference" the type is GlobalReference instead of ConceptDescription

Generate:
![image](https://github.com/eclipse-esmf/esmf-sdk/assets/59824205/d21be4db-c52b-4747-861b-71a0d02079f2)

**Comment by chris-volk** [comment]
Since the Aspect Model "see" reference is a URI without further semantic (no declaration whether external/internal) the bugfix is to keep "ExternalReference" as the standard mapping and set the type to GlobalReference as explained by @BirgitBoss.
