### ISSUE TITLE
[Task] Colored SAMM elements in generated diagrams

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-sdk#552]
As a user of the SDK I want any generated diagrams (png, .., within generated html doc of aspect, ..) to follow the SAMM coloring scheme 
from the editor, see also https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/pull/291.
I would also prefer to have them officially listed in https://github.com/eclipse-esmf/esmf-antora-ui/blob/main/docs/logo-and-color-palette/ESMF_description.md as SAMM element colors.

This issue also provides a mitigation for https://github.com/eclipse-esmf/esmf-sdk/issues/499 in the sense that the generated model will be easier to mentally process.

**Comment by chris-volk** [comment]
Regarding listing the colors, one idea is to distinguish between Overall layout colors and SAMM element colors as below:


```
| Scope        | Color sample                                                    | Hex value | What the color stands for |
|--------------|-----------------------------------------------------------------|-----------|----------|
| Overall - Consumption  | ![Consumption purple](images/esmf_color_consumption_purple.png) | #995FAB   | API Consumption in UI & backend – for example, the consumption of all required APIs in one UI, providing a user-friendly, semantics-aware software.|
| Overall - Provisioning | ![Provisioning blue](images/esmf_color_provisioning_blue.png)   | #8298E0   | The API provisioning (or: implementation) phase where at least one API is provided per Aspect Model to make semantic information available in a modular way. Also suitable for microservice-style software solutions.|
| Overall - Modeling    | ![Modeling blue-gray](images/esmf_color_modeling_bluegray.png)  | #8DA5BF   | The modeling phase where raw data is explained by creating Aspect Models.|
| Overall - Eclipse OSS  | ![Eclipse orange](images/esmf_color_eclipse_orange.png)         | #F88D2B   | SAMM, the Semantic Aspect Meta Model at the heart of the ESMF tools and the ESMF project at Eclipse. SAMM specifies how to express the meaning of data through Aspect Models in both a human- and machine-readable way.|
| SAMM Aspect    | ![Modeling blue-gray](images/esmf_color_modeling_bluegray.png)  | #8DA5BF   | The color of an Aspect |
```

**Comment by atextor** [comment]
> Regarding listing the colors, one idea is to distinguish between Overall layout colors and SAMM element colors as below:
> 
> ```
> | Scope        | Color sample                                                    | Hex value | What the color stands for |
> |--------------|-----------------------------------------------------------------|-----------|----------|
> | Overall - Consumption  | ![Consumption purple](images/esmf_color_consumption_purple.png) | #995FAB   | API Consumption in UI & backend – for example, the consumption of all required APIs in one UI, providing a user-friendly, semantics-aware software.|
> | Overall - Provisioning | ![Provisioning blue](images/esmf_color_provisioning_blue.png)   | #8298E0   | The API provisioning (or: implementation) phase where at least one API is provided per Aspect Model to make semantic information available in a modular way. Also suitable for microservice-style software solutions.|
> | Overall - Modeling    | ![Modeling blue-gray](images/esmf_color_modeling_bluegray.png)  | #8DA5BF   | The modeling phase where raw data is explained by creating Aspect Models.|
> | Overall - Eclipse OSS  | ![Eclipse orange](images/esmf_color_eclipse_orange.png)         | #F88D2B   | SAMM, the Semantic Aspect Meta Model at the heart of the ESMF tools and the ESMF project at Eclipse. SAMM specifies how to express the meaning of data through Aspect Models in both a human- and machine-readable way.|
> | SAMM Aspect    | ![Modeling blue-gray](images/esmf_color_modeling_bluegray.png)  | #8DA5BF   | The color of an Aspect |
> ```
> 
> It's also a consideration to rename https://github.com/eclipse-esmf/esmf-antora-ui/blob/main/docs/logo-and-color-palette/ESMF_description.md to /ESMF_color-definitions-and-logos to hint at providing the actual color definitions in this file

The file was [already renamed](https://github.com/eclipse-esmf/esmf-antora-ui/pull/18) to README.md so that it is immediately displayed when the folder is opened.
