### ISSUE TITLE
[Task] Refactoring tool: All Aspects with references to X

### ISSUE THREAD

**Issue by chris-volk** [eclipse-esmf/esmf-sdk#554]
Assume that I want to improve a basic model which is referred to (directly or indirectly) by multiple models.
The improvement is so important that I want to create new versions of all models that (directly or indirectly) refer to it.

So with the SDK I want to get 
- a list of all such models (e.g. from a github repository)
- if possible for each file a reference structure that explains to me how it indirectly refers to it, so that I can check and understand it
- if possible an additional option to create new versions of each file automatically (and a parameter that lets me decide if I want to count up the major, minor or bugfix version of it)

**Comment by atextor** [comment]
The last part of the bullet point is addressed in separate issue #645.
