### ISSUE TITLE
[BUG] Correctly translate IDTA submodel templates to SAMM

### ISSUE THREAD

**Issue by atextor** [eclipse-esmf/esmf-sdk#595]
**How: List of performed steps**
Translate IDTA [submodel-templates](https://github.com/admin-shell-io/submodel-templates) to valid Aspect Models.

**What: Actual result vs expected result**
Expected: All SMTs are correctly translated
Actual: Several SMTs can not be translated or are translated to invalid Aspect Models for various reasons:
* Failure to deserialize AASX
* Erroneous reference values that are no valid URI or IRDI are not escaped, leading to syntactically invalid RDF/Turtle
* Multiple descriptions translated without checks, leading to multiple samm:preferredName or samm:description assertions with the same language tag
* Translation of SMTs with Operations leads to `samm:properties` assertions that contain `samm:Operations`
* In certain cases, references to dataTypes (Entities) are created that don't exist

**Where: (e.g. component, version, url, your system info)**
AasToAspectModelGenerator

**Comment by BirgitBoss** [comment]
Even in cases a valid SAMM model is created the model does not correctly reflect the SMT:

- SMC and SML are converted to scalars
- data types are not considered, all scalars are xs:string

to just name the two most obvious issues.
