### ISSUE TITLE
[BUG] SAMM2AASX - incorrect serialization of Entities in Sets

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-esmf/esmf-sdk#603]
**How: List of performed steps**

This is the correct serialization of SMC in SML
![image](https://github.com/eclipse-esmf/esmf-sdk/assets/59824205/8f88bfd5-cf24-4377-a824-c27bda83c013)

```
 <submodelElements>
        <submodelElementList>
          <idShort>documentVersion</idShort>
          <typeValueListElement>SubmodelElement</typeValueListElement>
          <value>
            <submodelElementCollection>
              <value>
                <property>
                  <idShort>aScalar</idShort>
                  <valueType>xs:string</valueType>
                </property>
                <submodelElementList>
                  <idShort>anotherSet</idShort>
                  <typeValueListElement>SubmodelElement</typeValueListElement>
                  <value>
                    <property>
                      <idShort>aSclar</idShort>
                      <valueType>xs:string</valueType>
                    </property>
                  </value>
                </submodelElementList>
                <multiLanguageProperty>
                  <idShort>aMLP</idShort>
                  <value>
                    <langStringTextType>
                      <language>en</language>
                      <text></text>
                    </langStringTextType>
                  </value>
                </multiLanguageProperty>
              </value>
            </submodelElementCollection>
          </value>
        </submodelElementList>
      </submodelElements>
```

The generator generates (see value: submodelElementCollection etc. is missing before the second <aas:value>

```

<aas:submodelElementList>
          <aas:idShort>handoverDocumentation</aas:idShort>
          <aas:description>
            <aas:langStringTextType>
              <aas:language>en</aas:language>
              <aas:text>A set of relevant documents to hand over to customers for documentation purposes</aas:text>
            </aas:langStringTextType>
          </aas:description>
          <aas:orderRelevant>true</aas:orderRelevant>
          <aas:typeValueListElement>SubmodelElement</aas:typeValueListElement>
          <aas:value>
            <aas:idShort>HandoverDocumentationEntity</aas:idShort>
            <aas:value>
              <aas:submodelElementList>
```

see aspect model that was converted:
[aspect_model.zip](https://github.com/user-attachments/files/16128710/aspect_model.zip)

an easier example see here (.ttl example and corrected .xml-file)

[gen.zip](https://github.com/user-attachments/files/16130199/gen.zip)

**Comment by chris-volk** [comment]
This file could not be loaded in the package explorer

**Comment by chris-volk** [comment]
Additional info: The modified file Aspect3.ttl.aas_corrected.xml inside [gen.zip](https://github.com/user-attachments/files/16130199/gen.zip) (see above) is also recognized as erroneous by the current AAS test engine 0.4.0 (https://github.com/admin-shell-io/aas-test-engines)
[result_dump.txt](https://github.com/user-attachments/files/16280049/result_dump.txt)

**Comment by BirgitBoss** [comment]
[Aspect3.ttl.aas_corrected_fixed.xml.zip](https://github.com/user-attachments/files/16282266/Aspect3.ttl.aas_corrected_fixed.xml.zip)
I now fixed the xml within the aasx package explorer and saved it again.

To me it seems the validation tool cannot deal with `<aas:` refix
